title: Haoqun Wang's Homepage
page-top-title: Haoqun Wang
top-section-bg-text: Artificial Intelligence
home-subtitle: Haoqun Wang&ensp;|&ensp;王皓群
copyright-text: '&copy; Haoqun Wang 2025-2026. All Rights Reserved.'